# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###

# Create new user
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
  "name": "TestUser",
  "avatar": "some.jpg",
  "email": "fest@example.com",
  "isPro": true,
  "password": "qwerty"
}
###

#Get Offers
get http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
###

#Post Offers
POST  http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
    "price": 10280,
    "title": "Very very very splendid place.",
    "description": "It was good",
    "images": ["category-disk.jpg"],
    "type": "house",
    "city": "Paris",
    "date": "2024-05-30T03:39:12.729Z",
    "previewImage": "category-disk.jpg",
    "isPremium": true,
    "offerLatitude": 42.8566,
    "offerLongitude": 139.3895,
    "offerZoom": 16,
    "bedrooms": 2,
    "maxAdults": 4,
    "goods": ["tv"]
}
###

#Get Offer
get http://localhost:5000/offers/665bae93e7eab170c1094c26 HTTP/1.1
Content-Type: application/json
###

#Update Offer
PATCH http://localhost:5000/offers/665bae93e7eab170c1094c25 HTTP/1.1
Content-Type: application/json

{
  "price": 110
}
###

#Get favorites
GET http://localhost:5000/favorites HTTP/1.1
Content-Type: application/json

###

#ChangeFavorites
PATCH http://localhost:5000/favorites/6650f4cf1b81400365741b7e/0 HTTP/1.1
Content-Type: application/json

###

#Get Premiums
GET http://localhost:5000/premiumOffers/Paris HTTP/1.1
Content-Type: application/json

###


#Get Comments
GET http://localhost:5000/comments/6650f4cf1b81400365741b75 HTTP/1.1
Content-Type: application/json

###

#Add new Comment
POST http://localhost:5000/comments/6650f4cf1b81400365741b76 HTTP/1.1
Content-Type: application/json

{
  "date": "2024-06-04T01:29:12.729Z",
  "comment": "It was horrible",
  "rating": "2",
  "offerId": "6650f4cf1b81400365741b76"
}

###

POST http://localhost:5000/user/6650f4cf1b81400365741b71/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< H:\djangoboy\Projects\HA\avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
