# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###

# Create new user
POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
  "name": "TestUser",
  "avatar": "some.jpg",
  "email": "pest@example.com",
  "isPro": true,
  "password": "qwerty"
}
###

# Login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
  "email": "pest@example.com",
  "password": "qwerty"
}
###

# Check Auth
GET http://localhost:4000/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NjljZGVjZDk2ZjMzN2M3YjFhODEwYSIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTgyMTI0ODAsImV4cCI6MTcxODM4NTI4MH0.mc99EgKFNns3BdzBqRM-_-RUXLhkCw4oxrHANwVIrzw

###

#Get Offers
get http://localhost:5000/offers?count=40 HTTP/1.1
Content-Type: application/json

###

#Post Offers
POST  http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
    "price": 10280,
    "title": "Very very very splendid place.",
    "description": "Olddd dfkjdflkjlkjsdkfljsdflkjsdksdjflkdjfsldsjldsfj",
    "images": ["category-disk.jpg", "category-disk.jpg", "category-disk.jpg",
    "category-disk.jpg", "category-disk.jpg", "category-disk.jpg"],
    "type": "house",
    "city": "Amsterdam",
    "date": "2024-05-30T03:39:12.729Z",
    "previewImage": "category-disk.jpg",
    "isPremium": true,
    "offerLatitude": 42.8566,
    "offerLongitude": 139.3895,
    "offerZoom": 16,
    "bedrooms": 2,
    "maxAdults": 4,
    "goods": ["Breakfast", "Fridge"]
}
###

#Get Offer
get http://localhost:4000/offers/66699aedb04f254779abf332 HTTP/1.1
Content-Type: application/json
###

#Update Offer
PATCH http://localhost:5000/offers/666e0610f8b2a6423155b813 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NzFkNTU2MTgzNGExZGI0MzQxYzQ2NCIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTg3MzYyMzQsImV4cCI6MTcxODkwOTAzNH0.t2Okxf2Z_B7ifnWq0oeSFy4C_F8O6qBKiqP5NDblir4

{
  "maxAdults": 10
}
###

#Delete Offer
DELETE http://localhost:5000/offers/666e0610f8b2a6423155b813 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NzFkNTU2MTgzNGExZGI0MzQxYzQ2NCIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTg3MzYyMzQsImV4cCI6MTcxODkwOTAzNH0.t2Okxf2Z_B7ifnWq0oeSFy4C_F8O6qBKiqP5NDblir4

###

#Get favorites
GET http://localhost:4000/favorites HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6ImZlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NWJiMThkY2RkNjE4Y2IxMTY5ZjQ4ZiIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTgyMTIyNjEsImV4cCI6MTcxODM4NTA2MX0.ITMHQ_U-T_5m_DAdexgM1kKChp30PmyVcuvS99nebjI

###

#ChangeFavorites
POST http://localhost:5000/favorites/666e0610f8b2a6423155b801/2 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NzFkNTU2MTgzNGExZGI0MzQxYzQ2NCIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTg3MzYyMzQsImV4cCI6MTcxODkwOTAzNH0.t2Okxf2Z_B7ifnWq0oeSFy4C_F8O6qBKiqP5NDblir4


###

#Get Premiums
GET http://localhost:5000/premium/Dusseldorf HTTP/1.1
Content-Type: application/json

###


#Get Comments
GET http://localhost:4000/comments/66699aedb04f254779abf332 HTTP/1.1
Content-Type: application/json

###

#Add new Comment
POST http://localhost:5000/comments/666e0610f8b2a6423155b813 HTTP/1.1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NzFkNTU2MTgzNGExZGI0MzQxYzQ2NCIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTg3MzYyMzQsImV4cCI6MTcxODkwOTAzNH0.t2Okxf2Z_B7ifnWq0oeSFy4C_F8O6qBKiqP5NDblir4

{
  "date": "2024-06-04T01:29:12.729Z",
  "comment": "It was wonderful",
  "rating": 3
  }

###

#Upload avatar
POST http://localhost:4000/user/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NjljZGVjZDk2ZjMzN2M3YjFhODEwYSIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTgyMjc2MTAsImV4cCI6MTcxODQwMDQxMH0.8MWzjg8vBhKL978LwjzGBALrR_ogSb60Jq9YPPsrqtY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< H:\djangoboy\Projects\HA\avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

#Upload preview
POST http://localhost:4000/offers/66699aedb04f254779abf332/preview HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGVzdFVzZXIiLCJlbWFpbCI6InBlc3RAZXhhbXBsZS5jb20iLCJpZCI6IjY2NjljZGVjZDk2ZjMzN2M3YjFhODEwYSIsImlzUHJvIjp0cnVlLCJpYXQiOjE3MTgyMjc2MTAsImV4cCI6MTcxODQwMDQxMH0.8MWzjg8vBhKL978LwjzGBALrR_ogSb60Jq9YPPsrqtY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< H:\djangoboy\Projects\HA\avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
